### ISSUE TITLE
Feature: User can take a quiz

### ISSUE THREAD

**Issue by PaxtonRosenberg** [PaxtonRosenberg/SportIQ#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
users will be able to view quiz questions, answer them and see their results

User can take a quiz
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

upon visiting the page, a user will see a quiz question that they are able to answer, after selecting a response, the user will be given feedback to see if they answer was correct or incorrect before moving onto the next question. After answering all of the questions, the user will be able to see their overall results.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-01-28 at 11 44 17 PM](https://github.com/PaxtonRosenberg/SportIQ/assets/146014772/252d926c-9cf4-4648-a4af-6180d0af9863)
![Screenshot 2024-01-28 at 11 44 52 PM](https://github.com/PaxtonRosenberg/SportIQ/assets/146014772/b5e93da7-99e1-4710-96c8-cff23fd7cc5b)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] add daily quiz, quiz questions and question answers into the database

### ☁️ Server Tasks

- [ ] setup GET requests to the dailyQuizzes, dailyQuizQuestions and dailyQuizAnswers tables in order to retrieve data to populate quizzes

### ⚡ Client Tasks

- [ ] Create a component to display the question as well as an indicator to let the user know what question they are on
- [ ] Create a component to display the answers to the question displayed
- [ ] add feedback to the answers component to let the user know if their selection is right or wrong.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
