### ISSUE TITLE
Feature: User can create and view their own quizzes

### ISSUE THREAD

**Issue by PaxtonRosenberg** [PaxtonRosenberg/SportIQ#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

users will be able to created their own quizzes for other users to take. They will also be able to view the quizzes they've created on their "my quizzes" page and will be able to see other quizzes, including their own, on the community quizzes page. By clicking on a quiz they will be able to take that particular quiz.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

users will submit a form that sends quiz data to the database, using that data, their quiz will be visible and able to be taken
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="719" alt="Screenshot 2024-02-08 at 8 15 33 PM" src="https://github.com/PaxtonRosenberg/SportIQ/assets/146014772/a601a68a-0b9e-4c47-ad98-5686e32c2a46">
<img width="716" alt="Screenshot 2024-02-08 at 8 15 51 PM" src="https://github.com/PaxtonRosenberg/SportIQ/assets/146014772/e706943a-d8e2-41c3-a84a-b15b05cd2965">
<img width="718" alt="Screenshot 2024-02-08 at 8 16 12 PM" src="https://github.com/PaxtonRosenberg/SportIQ/assets/146014772/67a55656-f6b5-4684-b786-20eba0fae52b">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] create an add quizId function to add data to the userQuizzes table
- [ ] create an add quiz questions function to add data to the userQuizQuestions table
- [ ] create an add answers function to add data to the userQuizAnswers table

### ⚡ Client Tasks

- [ ] Create a component to house community quizzes
- [ ] Create component house user quiz submission form
- [ ] allow component to send data to the server and then to the database
- [ ] Create a page to house finished user quizzes.
- [ ] Make quizzes clickable so that they are able to be taken in the same way as the main quiz

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
