### ISSUE TITLE
Feature: User can update and delete submitted quizzes

### ISSUE THREAD

**Issue by PaxtonRosenberg** [PaxtonRosenberg/SportIQ#24]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to edit or delete quizzes that they have created
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click a pencil icon next to their created quiz on the my quizzes page. It will take them back to the form where they can edit and save updates or choose to delete the quiz altogether.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] no tasks in the database

### ☁️ Server Tasks

- [ ] create a put request to the userQuizQuestions and userQuizAnswers table to update entries
- [ ] create delete requests to the userQuizzes, userQuizQuestions and userQuizAnswers tables

### ⚡ Client Tasks

- [ ] update myQuizzes component to make the edit icon clickable
- [ ] update the form to handle edits and deletions

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
