### ISSUE TITLE
Feature: User can create an account and sign in

### ISSUE THREAD

**Issue by PaxtonRosenberg** [PaxtonRosenberg/SportIQ#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can create an account and sign in
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click an icon that takes them to a login/sign up screen, their account will allow their results to be tracked and allow them to create quizzes
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2024-01-30 at 9 54 13 PM](https://github.com/PaxtonRosenberg/SportIQ/assets/146014772/7ef8efc6-d3e9-43e4-a852-73abf79de672)
![Screenshot 2024-01-30 at 9 55 35 PM](https://github.com/PaxtonRosenberg/SportIQ/assets/146014772/d62dee1a-a2a5-4b8e-9ae6-6e8a47f1ead4)

## ✅ Task Lists

> ####

# Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] update database with user info after login/sign-up

### ☁️ Server Tasks

- [ ] create post request for authorization

### ⚡ Client Tasks

- [ ] add functionality to avatar icon and create sign-up/login modal

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
